### ISSUE TITLE
无法运行demo

### ISSUE THREAD

**Issue by pu943980293** [jpush/jchat-windows#1]
2>c1xx : fatal error C1083: 无法打开源文件: “GeneratedFiles\Release\moc_ItemWidgetVoiceLeft.cpp”: No such file or directory
2>moc_ItemWidgetVoiceRight.cpp
2>c1xx : fatal error C1083: 无法打开源文件: “GeneratedFiles\Release\moc_ItemWidgetVoiceRight.cpp”: No such file or directory
2>moc_Label.cpp
2>moc_LoginWidget.cpp
2>c1xx : fatal error C1083: 无法打开源文件: “GeneratedFiles\Release\moc_LoginWidget.cpp”: No such file or directory
2>moc_MainWidget.cpp
2>c1xx : fatal error C1083: 无法打开源文件: “GeneratedFiles\Release\moc_MainWidget.cpp”: No such file or directory
2>moc_MemberItemWidget.cpp
2>moc_MemberModel.cpp
2>c1xx : fatal error C1083: 无法打开源文件: “GeneratedFiles\Release\moc_MemberModel.cpp”: No such file or directory
2>moc_MessageListWidget.cpp
2>c1xx : fatal error C1083: 无法打开源文件: “GeneratedFiles\Release\moc_MessageListWidget.cpp”: No such file or directory
报这类错，是什么原因呢

**Comment by lethe555** [comment]
安装Qt插件了吗, 插件有没有设置Qt版本, 右键解决方案菜单,重新设置下解决方案的Qt版本
